<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>$(PluginTargetFramework);$(PortableTargetFramework)</TargetFrameworks>
    <RootNamespace>JMCL.Azure.Secrets</RootNamespace>
    <AssemblyName>JMCL.Azure.Secrets</AssemblyName>
    <PackageId>JMCL.Azure.Secrets</PackageId>
    <Title>JMCL.Azure.Secrets</Title>
    <Description>Secret retrieval for constrained hosts.</Description>
    <PackageTags>azure;secrets;keyvault</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\JMCL.Core.IocContainer\JMCL.Core.IocContainer.csproj" />
    <ProjectReference Include="..\JMCL.Core.ProcessModel\JMCL.Core.ProcessModel.csproj" />
    <ProjectReference Include="..\JMCL.Core.Net\JMCL.Core.Net.csproj" />
    <ProjectReference Include="..\JMCL.Core.RestClient\JMCL.Core.RestClient.csproj" />
    <ProjectReference Include="..\JMCL.Core.Serialization\JMCL.Core.Serialization.csproj" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == '$(PluginTargetFramework)'">
    <Reference Include="System.Net.Http" />
  </ItemGroup>

</Project>
